Script started on Fri 23 Jan 2015 11:46:37 PM PST
~
vgarc018@hammer $ cd CS100/rshell/
~/CS100/rshell
vgarc018@hammer $ make
g++ -Wall -Werror -ansi -pedantic ./src/rshell.cpp -o ./bin/rshell
~/CS100/rshell
vgarc018@hammer $ bin/rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test for comments
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #this is not going to show up
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ # 
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ 
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ 
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test for just enter input
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ 
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ 
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ 
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test for command       single commands
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls
bin  exec.script  LICENSE  Makefile  README.md	src
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls  pwd
/home/csmajs/vgarc018/CS100/rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ echo hello
hello
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ mkdir test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls
bin  exec.script  LICENSE  Makefile  README.md	src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test for flag
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls -l
total 40
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:43 bin
-rw------- 1 vgarc018 csmajs     0 Jan 23 23:43 exec.script
-rw------- 1 vgarc018 csmajs 18027 Jan 23 23:39 LICENSE
-rw-r--r-- 1 vgarc018 csmajs   155 Jan 23 23:39 Makefile
-rw------- 1 vgarc018 csmajs   436 Jan 23 23:39 README.md
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:39 src
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:45 test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls -a
.  ..  bin  exec.script  .git  LICENSE	Makefile  README.md  src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls -a -l -r
total 52
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:45 test
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:39 src
-rw------- 1 vgarc018 csmajs   436 Jan 23 23:39 README.md
-rw-r--r-- 1 vgarc018 csmajs   155 Jan 23 23:39 Makefile
-rw------- 1 vgarc018 csmajs 18027 Jan 23 23:39 LICENSE
drwx------ 8 vgarc018 csmajs  4096 Jan 23 23:40 .git
-rw------- 1 vgarc018 csmajs     0 Jan 23 23:43 exec.script
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:43 bin
drwx------ 7 vgarc018 csmajs  4096 Jan 23 23:39 ..
drwx------ 6 vgarc018 csmajs  4096 Jan 23 23:45 .
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test with alot of c flags
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls -a -0a  a -a 0a  -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a -a a 
.  ..  bin  exec.script  .git  LICENSE	Makefile  README.md  src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ test with           #test for nothig        random letters
'/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ kfdjabhsd;fkljbhasdf
Error in exec: No such file or directory
Error in exec: No such file or directory
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ akdsjbf;aksdjfbasd;kjfb
Error in exec: No such file or directory
Error in exec: No such file or directory
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ kasdjbfsdkbfdshfbdhsbfd
Error in exec: No such file or directory
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ shdfbsjdhbfsdhfbshdbfhsdbfhsdf
Error in exec: No such file or directory
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ hdsbfjshdbfshdfbhsdfbhsdbfhdsbf
Error in exec: No such file or directory
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ hsdbfjhsdbfhsdbfhdsbfhsdbfhsd
Error in exec: No such file or directory
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ jfbsdkhfbsdhfbsdjbhfsdjfbhdshbfhsdbfhdbfhbsdfhbsdhfbhsdbfhjsdbfhdsbfhsdbhbsdhbfhsbfhjsdbfhbsdhbfhsdbfhbdsfhbsdhfbsdhbfhsdbfhsdbfjhsdbfhbsdfhbsdhfhsdbfhjsdbfhbsdhfbshdbfhsdbfhbsdhfbsdhfbsdhjfbshdbfhjsdbfjhbsdfhbsdhfbhsdbfhjdsbfjhsdbfhjsbdfhjsdbfjhsdbfjhbsdfhbsdfhjbdfhbsdhfbsdbhf
Error in exec: File name too long
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test wioth comm        th comments in the commands
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls -a #-l
.  ..  bin  exec.script  .git  LICENSE	Makefile  README.md  src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ pwd #this is not good
/home/csmajs/vgarc018/CS100/rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test with really long glad=     argi ument
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls -mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
bin, exec.script, LICENSE, Makefile, README.md, src, test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls -lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll
total 40
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:43 bin
-rw------- 1 vgarc018 csmajs     0 Jan 23 23:43 exec.script
-rw------- 1 vgarc018 csmajs 18027 Jan 23 23:39 LICENSE
-rw-r--r-- 1 vgarc018 csmajs   155 Jan 23 23:39 Makefile
-rw------- 1 vgarc018 csmajs   436 Jan 23 23:39 README.md
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:39 src
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:45 test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ -l ls     #test with glags       g flags first
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ -a ls
Error in exec: No such file or directory
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ -l ls
Error in exec: No such file or directory
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test of ls thrww  ee time   s   es no connector
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls ls ls ls
ls: cannot access ls: No such file or directory
ls: cannot access ls: No such file or directory
ls: cannot access ls: No such file or directory
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test for random spaces
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$                                        ls                                   -a -l
total 52
drwx------ 6 vgarc018 csmajs  4096 Jan 23 23:45 .
drwx------ 7 vgarc018 csmajs  4096 Jan 23 23:39 ..
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:43 bin
-rw------- 1 vgarc018 csmajs     0 Jan 23 23:43 exec.script
drwx------ 8 vgarc018 csmajs  4096 Jan 23 23:40 .git
-rw------- 1 vgarc018 csmajs 18027 Jan 23 23:39 LICENSE
-rw-r--r-- 1 vgarc018 csmajs   155 Jan 23 23:39 Makefile
-rw------- 1 vgarc018 csmajs   436 Jan 23 23:39 README.md
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:39 src
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:45 test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$                                                                               ls                                                                              -a                                                           
.  ..  bin  exec.script  .git  LICENSE	Makefile  README.md  src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$                                                     ls                                                 -l                                             
total 40
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:43 bin
-rw------- 1 vgarc018 csmajs     0 Jan 23 23:43 exec.script
-rw------- 1 vgarc018 csmajs 18027 Jan 23 23:39 LICENSE
-rw-r--r-- 1 vgarc018 csmajs   155 Jan 23 23:39 Makefile
-rw------- 1 vgarc018 csmajs   436 Jan 23 23:39 README.md
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:39 src
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:45 test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$                               ls                         -a                          -l
total 52
drwx------ 6 vgarc018 csmajs  4096 Jan 23 23:45 .
drwx------ 7 vgarc018 csmajs  4096 Jan 23 23:39 ..
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:43 bin
-rw------- 1 vgarc018 csmajs     0 Jan 23 23:43 exec.script
drwx------ 8 vgarc018 csmajs  4096 Jan 23 23:40 .git
-rw------- 1 vgarc018 csmajs 18027 Jan 23 23:39 LICENSE
-rw-r--r-- 1 vgarc018 csmajs   155 Jan 23 23:39 Makefile
-rw------- 1 vgarc018 csmajs   436 Jan 23 23:39 README.md
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:39 src
drwx------ 2 vgarc018 csmajs  4096 Jan 23 23:45 test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ;;;;;;;;        #test for connectors
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ;;  ls  ;ls
bin  exec.script  LICENSE  Makefile  README.md	src  test
bin  exec.script  LICENSE  Makefile  README.md	src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls & ls
bin  exec.script  LICENSE  Makefile  README.md	src  test
bin  exec.script  LICENSE  Makefile  README.md	src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls || ls
bin  exec.script  LICENSE  Makefile  README.md	src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls;pwd
bin  exec.script  LICENSE  Makefile  README.md	src  test
/home/csmajs/vgarc018/CS100/rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ true && ls
bin  exec.script  LICENSE  Makefile  README.md	src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ false && ls
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ true        &&ls
bin  exec.script  LICENSE  Makefile  README.md	src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ;;;;;;;;;;;;;&&&&&&&&&&&|||||||
Segmentation fault
~/CS100/rshell
vgarc018@hammer $ bin/rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #the prograsm    m give a seg fault when random connectr ors typoed i     ed in
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test to see if i can run rshell with in rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ bin/rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ bin/rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ bin/rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #see if the rshell with in 2 others works
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls
bin  exec.script  LICENSE  Makefile  README.md	src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls -a
.  ..  bin  exec.script  .git  LICENSE	Makefile  README.md  src  test
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ pwd
/home/csmajs/vgarc018/CS100/rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$   echo hello
hello
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ ls -r
test  src  README.md  Makefile	LICENSE  exec.script  bin
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #test the exit command       out of all of the shells
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ exit
Thanks for using Rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ exit
Thanks for using Rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ exit
Thanks for using Rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ exit
Thanks for using Rshell
~/CS100/rshell
vgarc018@hammer $ bin/rshell
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ #the pro       the program works 
/home/csmajs/vgarc018/CS100/rshell
vgarc018@hammer.cs.ucr.edu$ true && true || false
Error in exec: No such file or directory
*** glibc detected *** bin/rshell: corrupted double-linked list: 0x0000000001520ed0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3296875e66]
/lib64/libc.so.6[0x3296876270]
/lib64/libc.so.6[0x3296878948]
/lib64/libc.so.6(fclose+0x14d)[0x32968664cd]
/lib64/libnss_files.so.2(_nss_files_getpwuid_r+0x15a)[0x7f0fb46890ea]
/lib64/libc.so.6(getpwuid_r+0xdd)[0x32968abdcd]
/lib64/libc.so.6[0x32968ae0e4]
/lib64/libc.so.6(getlogin+0x15)[0x32968addc5]
bin/rshell[0x402803]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x329681ed5d]
bin/rshell[0x4015d9]
======= Memory map: ========
00400000-0040a000 r-xp 00000000 00:17 17369925                           /home/csmajs/vgarc018/CS100/rshell/bin/rshell
0060a000-0060b000 rw-p 0000a000 00:17 17369925                           /home/csmajs/vgarc018/CS100/rshell/bin/rshell
0151f000-01540000 rw-p 00000000 00:00 0                                  [heap]
3296400000-3296420000 r-xp 00000000 08:01 13631535                       /lib64/ld-2.12.so
329661f000-3296620000 r--p 0001f000 08:01 13631535                       /lib64/ld-2.12.so
3296620000-3296621000 rw-p 00020000 08:01 13631535                       /lib64/ld-2.12.so
3296621000-3296622000 rw-p 00000000 00:00 0 
3296800000-329698a000 r-xp 00000000 08:01 13631614                       /lib64/libc-2.12.so
329698a000-3296b8a000 ---p 0018a000 08:01 13631614                       /lib64/libc-2.12.so
3296b8a000-3296b8e000 r--p 0018a000 08:01 13631614                       /lib64/libc-2.12.so
3296b8e000-3296b8f000 rw-p 0018e000 08:01 13631614                       /lib64/libc-2.12.so
3296b8f000-3296b94000 rw-p 00000000 00:00 0 
3296c00000-3296c83000 r-xp 00000000 08:01 13632299                       /lib64/libm-2.12.so
3296c83000-3296e82000 ---p 00083000 08:01 13632299                       /lib64/libm-2.12.so
3296e82000-3296e83000 r--p 00082000 08:01 13632299                       /lib64/libm-2.12.so
3296e83000-3296e84000 rw-p 00083000 08:01 13632299                       /lib64/libm-2.12.so
329c800000-329c816000 r-xp 00000000 08:01 13631527                       /lib64/libgcc_s-4.4.7-20120601.so.1
329c816000-329ca15000 ---p 00016000 08:01 13631527                       /lib64/libgcc_s-4.4.7-20120601.so.1
329ca15000-329ca16000 rw-p 00015000 08:01 13631527                       /lib64/libgcc_s-4.4.7-20120601.so.1
32a0000000-32a00e8000 r-xp 00000000 08:01 9179168                        /usr/lib64/libstdc++.so.6.0.13
32a00e8000-32a02e8000 ---p 000e8000 08:01 9179168                        /usr/lib64/libstdc++.so.6.0.13
32a02e8000-32a02ef000 r--p 000e8000 08:01 9179168                        /usr/lib64/libstdc++.so.6.0.13
32a02ef000-32a02f1000 rw-p 000ef000 08:01 9179168                        /usr/lib64/libstdc++.so.6.0.13
32a02f1000-32a0306000 rw-p 00000000 00:00 0 
32a6400000-32a6416000 r-xp 00000000 08:01 13632327                       /lib64/libnsl-2.12.so
32a6416000-32a6615000 ---p 00016000 08:01 13632327                       /lib64/libnsl-2.12.so
32a6615000-32a6616000 r--p 00015000 08:01 13632327                       /lib64/libnsl-2.12.so
32a6616000-32a6617000 rw-p 00016000 08:01 13632327                       /lib64/libnsl-2.12.so
32a6617000-32a6619000 rw-p 00000000 00:00 0 
7f0fb4477000-7f0fb4481000 r-xp 00000000 08:01 13631519                   /lib64/libnss_nis-2.12.so
7f0fb4481000-7f0fb4680000 ---p 0000a000 08:01 13631519                   /lib64/libnss_nis-2.12.so
7f0fb4680000-7f0fb4681000 r--p 00009000 08:01 13631519                   /lib64/libnss_nis-2.12.so
7f0fb4681000-7f0fb4682000 rw-p 0000a000 08:01 13631519                   /lib64/libnss_nis-2.12.so
7f0fb4682000-7f0fb468e000 r-xp 00000000 08:01 13631789                   /lib64/libnss_files-2.12.so
7f0fb468e000-7f0fb488e000 ---p 0000c000 08:01 13631789                   /lib64/libnss_files-2.12.so
7f0fb488e000-7f0fb488f000 r--p 0000c000 08:01 13631789                   /lib64/libnss_files-2.12.so
7f0fb488f000-7f0fb4890000 rw-p 0000d000 08:01 13631789                   /lib64/libnss_files-2.12.so
7f0fb4890000-7f0fb4895000 rw-p 00000000 00:00 0 
7f0fb48aa000-7f0fb48ae000 rw-p 00000000 00:00 0 
7fffc0f5d000-7fffc0f73000 rw-p 00000000 00:00 0                          [stack]
7fffc0fbb000-7fffc0fbc000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted
~/CS100/rshell
vgarc018@hammer $ exit[K[K[K[Kexit
exit

Script done on Fri 23 Jan 2015 11:59:21 PM PST
