Script started on Sun 22 Feb 2015 11:52:56 PM PST
~
vgarc018@hammer $ cs100
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.  Everything you do is being   |
| recorded to measure your progress in the class.                             |
|                                                                             |
| Important commands for the class:                                           |
|   * calcgrade.sh          displays a detailed breakdown of your grade       |
|   * typespeed             practice typing unix commands                     |
|                                                                             |
| Important commands for general C++ programming:                             |
|   * make                  don't call g++ manually; let make do the work!    |
|   * gdb                   the GNU debugger                                  |
|   * valgrind              get rid of your memory leaks                      |
|   * cppcheck              static analysis tool                              |
|   * man                   find help about any syscall / terminal command    |
|                                                                             |
===============================================================================
[0m
[s%%%%%%%%%%[u[0;32mvgarc018[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m ls
a.out  C:\nppdf32Log\debuglog.txt  CS100  CS14	Desktop    fmt.h     ps1.cpp  rshell  ucr-cs100
check  cs10			   cs12   CS61	Downloads  gitlearn  q.cpp    TEST    WINDOWS
[s%%%%%%%%%%[u[0;32mvgarc018[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cd CS100/r[Kredir/ls[K[K
[s%%%%%%%%%%[u[0;32mvgarc018[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/redir[0;95m [0;36m$[0m cd rshell/
[s%%%%%%%%%%[u[0;32mvgarc018[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/redir/rshell[0;95m (master) [0;36m$[0m ls
bin  LICENSE  Makefile	README.md  src	test
[s%%%%%%%%%%[u[0;32mvgarc018[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/redir/rshell[0;95m (master) [0;36m$[0m make
g++ -Wall -Werror -ansi -pedantic ./src/rshell.cpp -o ./bin/rshell
g++ -Wall -Werror -ansi -pedantic ./src/ls.cpp -o ./bin/ls
g++ -Wall -Werror -ansi -pedantic ./src/cp.cpp -o ./bin/cp
[s%%%%%%%%%%[u[0;32mvgarc018[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/redir/rshell[0;95m (master) [0;36m$[0m bin/rshell 
/home/csmajs/vgarc018/CS100/redir/rshell
vgarc018@hammer.cs.ucr.edu$ #testing for output
/home/csmajs/vgarc018/CS100/redir/rshell
vgarc018@hammer.cs.ucr.edu$ cat Makefule   ile > tes
/home/csmajs/vgarc018/CS100/redir/rshell
vgarc018@hammer.cs.ucr.edu$ cat tes
SRCDIR=./src
BINDIR=./bin

all:
	@mkdir -p $(BINDIR)
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/rshell.cpp -o $(BINDIR)/rshell
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/ls.cpp -o $(BINDIR)/ls
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/cp.cpp -o $(BINDIR)/cp

clean:
	@rm -r $(BINDIR)
/home/csmajs/vgarc018/CS100/redir/rshell
vgarc018@hammer.cs.ucr.edu$ cat     ls >> tes
/home/csmajs/vgarc018/CS100/redir/rshell
vgarc018@hammer.cs.ucr.edu$ ls
bin  LICENSE  Makefile	README.md  src	tes  test
/home/csmajs/vgarc018/CS100/redir/rshell
vgarc018@hammer.cs.ucr.edu$ cat tes
SRCDIR=./src
BINDIR=./bin

all:
	@mkdir -p $(BINDIR)
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/rshell.cpp -o $(BINDIR)/rshell
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/ls.cpp -o $(BINDIR)/ls
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/cp.cpp -o $(BINDIR)/cp

clean:
	@rm -r $(BINDIR)
SRCDIR=./src
BINDIR=./bin

all:
	@mkdir -p $(BINDIR)
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/rshell.cpp -o $(BINDIR)/rshell
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/ls.cpp -o $(BINDIR)/ls
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/cp.cpp -o $(BINDIR)/cp

clean:
	@rm -r $(BINDIR)
/home/csmajs/vgarc018/CS100/redir/rshell
vgarc018@hammer.cs.ucr.edu$ cat     #testing for input
/home/csmajs/vgarc018/CS100/redir/rshell
vgarc018@hammer.cs.ucr.edu$ cat < Makefile
SRCDIR=./src
BINDIR=./bin

all:
	@mkdir -p $(BINDIR)
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/rshell.cpp -o $(BINDIR)/rshell
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/ls.cpp -o $(BINDIR)/ls
	g++ -Wall -Werror -ansi -pedantic $(SRCDIR)/cp.cpp -o $(BINDIR)/cp

clean:
	@rm -r $(BINDIR)
/home/csmajs/vgarc018/CS100/redir/rshell
vgarc018@hammer.cs.ucr.edu$ #testing for b piping
/home/csmajs/vgarc018/CS100/redir/rshell
vgarc018@hammer.cs.ucr.edu$ ls | cat
q[i] = ls
q[i] = cat
Segmentation fault
[s%%%%%%%%%%[u[0;32mvgarc018[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/redir/rshell[0;95m (master) [0;36m$[0m exit
exit
~
vgarc018@hammer $ exit
exit

Script done on Sun 22 Feb 2015 11:56:02 PM PST
